name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build go app
      run: make all

    - name: Build web app
      run: |
        cd web
        npm install
        npm run build

#    - name: Test
#      run: go test -v ./...
